from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Any

# Stored under the same `.archmap/` convention archmap.cache already uses for
# the on-disk analysis cache, so a project only needs one generated-artifacts
# directory to gitignore (or commit — see docs/cli/memory.md).
DEFAULT_MEMORY_RELATIVE_PATH = ".archmap/memory.md"

_MAX_LIST_ITEMS = 10
_TIMESTAMP_LINE = re.compile(r"^_Generated:.*$", re.MULTILINE)


def digest_changed(existing: str | None, new: str) -> bool:
    """True if `new` differs from `existing` in anything but the timestamp.

    Lets callers skip rewriting the memory file (and touching its mtime,
    which would show up as a no-op git diff on every PostToolUse hook run)
    when nothing about the project's architecture actually changed.
    """
    if existing is None:
        return True
    return _TIMESTAMP_LINE.sub("", existing) != _TIMESTAMP_LINE.sub("", new)


def generate_memory_digest(report: dict[str, Any]) -> str:
    """Render a compact, token-efficient markdown snapshot of an analyzed
    project's architecture — health, risks, cycles, violations.

    Meant to be read by an AI coding agent (Claude Code and friends) at the
    start of a session instead of re-exploring the codebase from scratch:
    every fact here is already computed by `archmap analyze`, this just
    condenses it into prose an agent can skim in one read. Deterministic
    given the same report, so re-running `archmap memory` after a no-op
    change reproduces byte-identical output.
    """
    metrics = report.get("metrics", {})
    risks = report.get("risks", {})
    architecture = report.get("architecture", {})
    cycles = report.get("cycles", [])
    health = architecture.get("health", {})
    style = architecture.get("detectedStyle", {})

    lines: list[str] = [
        "# ArchMAP Project Memory",
        "",
        "_Auto-generated by `archmap memory` — do not edit by hand; "
        "regenerate with `archmap memory`._",
        f"_Generated: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        "## Health",
        (
            f"- Score: **{health.get('score', 0)}/100** ({health.get('grade', '?')}) — "
            f"{health.get('summary', '')}"
        ),
        f"- Style: **{style.get('name', 'unknown')}** (confidence {style.get('confidence', 0)})",
        (
            f"- Files: {metrics.get('filesAnalyzed', 0)} | "
            f"Dependencies: {metrics.get('totalDependencies', 0)} | "
            f"External packages: {metrics.get('externalDependencies', 0)}"
        ),
        (
            f"- Cycles: {len(cycles)} | "
            f"God modules: {len(risks.get('god_modules', []))} | "
            f"Layer violations: {len(risks.get('layer_violations', []))} | "
            f"Custom rule violations: {len(architecture.get('ruleViolations', []))}"
        ),
    ]
    if health.get("drivers"):
        lines.append(f"- Score drivers: {', '.join(health['drivers'])}")
    lines.append("")

    detected_layers = architecture.get("detectedLayers", [])
    if detected_layers:
        lines += ["## Detected layers", ", ".join(detected_layers), ""]

    top_risk_files = risks.get("top_risk_files", [])[:_MAX_LIST_ITEMS]
    if top_risk_files:
        lines.append("## Top risk files")
        for item in top_risk_files:
            signals = ", ".join(item.get("signals", [])) or "none"
            lines.append(
                f"- `{item.get('file')}` — risk {item.get('riskScore', 0)} "
                f"(dependents: {item.get('dependents', 0)}, "
                f"outgoing: {item.get('outgoing', 0)}; {signals})"
            )
        lines.append("")

    if cycles:
        lines.append("## Circular dependencies")
        for cycle in cycles[:_MAX_LIST_ITEMS]:
            lines.append("- " + " → ".join(cycle) + " → (back to start)")
        if len(cycles) > _MAX_LIST_ITEMS:
            lines.append(f"- ...and {len(cycles) - _MAX_LIST_ITEMS} more")
        lines.append("")

    layer_violations = risks.get("layer_violations", [])[:_MAX_LIST_ITEMS]
    if layer_violations:
        lines.append("## Layer violations")
        for violation in layer_violations:
            lines.append(
                f"- `{violation['source']}` ({violation['sourceLayer']}) → "
                f"`{violation['target']}` ({violation['targetLayer']}) — {violation['rule']}"
            )
        lines.append("")

    rule_violations = architecture.get("ruleViolations", [])[:_MAX_LIST_ITEMS]
    if rule_violations:
        lines.append("## Custom architecture rule violations")
        for violation in rule_violations:
            lines.append(f"- {violation['message']}")
        lines.append("")

    god_modules = risks.get("god_modules", [])[:_MAX_LIST_ITEMS]
    if god_modules:
        lines.append("## God modules")
        for module in god_modules:
            lines.append(f"- `{module['file']}` — {module['outgoing']} outgoing dependencies")
        lines.append("")

    lines += [
        "## For AI agents",
        (
            "- This file is a pre-computed snapshot — trust it over re-exploring the "
            "codebase from scratch. It refreshes automatically after edits if the "
            "PostToolUse hook from `archmap memory --help` is wired up; otherwise "
            "re-run `archmap memory` after structural changes."
        ),
        (
            "- For live, per-file detail beyond this snapshot, use the `archmap mcp` "
            "server tools: `get_file_context`, `impact_analysis`, `trace_reachability`, "
            "`run_checks`, `diff_architecture`, `get_network_exposure`."
        ),
        "",
    ]

    return "\n".join(lines)
