from __future__ import annotations

import argparse
from pathlib import Path

import pytest

from archmap.cli.commands import run_init


def _make_args(path: str, *, dry_run: bool = False, force: bool = False) -> argparse.Namespace:
    return argparse.Namespace(path=path, dry_run=dry_run, force=force)


# ---------------------------------------------------------------------------
# Fresh write
# ---------------------------------------------------------------------------


def test_init_creates_config_file(tmp_path: Path) -> None:
    args = _make_args(str(tmp_path))
    rc = run_init(args)

    assert rc == 0
    config = tmp_path / ".archmap.toml"
    assert config.is_file(), "Config file should have been created"
    content = config.read_text(encoding="utf-8")
    assert "[analysis]" in content
    assert "ignore_dirs" in content
    assert "[architecture.rules]" in content
    assert "[risks.layer_order]" in content


def test_init_detects_known_ignore_dirs(tmp_path: Path) -> None:
    (tmp_path / "node_modules").mkdir()
    (tmp_path / ".venv").mkdir()
    (tmp_path / "src").mkdir()

    args = _make_args(str(tmp_path))
    run_init(args)

    content = (tmp_path / ".archmap.toml").read_text(encoding="utf-8")
    # Both node_modules and .venv are in KNOWN_IGNORE → appear in ignore_dirs
    assert '"node_modules"' in content
    assert '".venv"' in content
    # src/ is not ignorable → becomes a layer candidate comment
    assert "# src" in content


def test_init_suggests_layer_candidates(tmp_path: Path) -> None:
    (tmp_path / "api").mkdir()
    (tmp_path / "core").mkdir()
    (tmp_path / "utils").mkdir()

    args = _make_args(str(tmp_path))
    run_init(args)

    content = (tmp_path / ".archmap.toml").read_text(encoding="utf-8")
    # Candidates become commented suggestions inside [risks.layer_order]
    assert "# api" in content
    assert "# core" in content
    assert "# utils" in content


# ---------------------------------------------------------------------------
# --dry-run
# ---------------------------------------------------------------------------


def test_init_dry_run_does_not_create_file(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    args = _make_args(str(tmp_path), dry_run=True)
    rc = run_init(args)

    assert rc == 0
    assert not (tmp_path / ".archmap.toml").exists(), "Dry-run must not write a file"
    captured = capsys.readouterr()
    assert "[analysis]" in captured.out


def test_init_dry_run_prints_valid_content(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    (tmp_path / "dist").mkdir()
    args = _make_args(str(tmp_path), dry_run=True)
    run_init(args)

    captured = capsys.readouterr()
    assert "ignore_dirs" in captured.out
    assert "[risks.layer_order]" in captured.out


# ---------------------------------------------------------------------------
# Conflict without --force
# ---------------------------------------------------------------------------


def test_init_aborts_if_config_exists(tmp_path: Path) -> None:
    existing = tmp_path / ".archmap.toml"
    existing.write_text("# original\n", encoding="utf-8")

    args = _make_args(str(tmp_path))
    rc = run_init(args)

    assert rc == 1
    # Original content must be untouched
    assert existing.read_text(encoding="utf-8") == "# original\n"


# ---------------------------------------------------------------------------
# Conflict with --force
# ---------------------------------------------------------------------------


def test_init_force_overwrites_existing_config(tmp_path: Path) -> None:
    existing = tmp_path / ".archmap.toml"
    existing.write_text("# original\n", encoding="utf-8")

    args = _make_args(str(tmp_path), force=True)
    rc = run_init(args)

    assert rc == 0
    content = existing.read_text(encoding="utf-8")
    assert "Generated by" in content
    assert content != "# original\n"
