from __future__ import annotations

from archmap.core.analyzer.architecture_suggester import (
    generate_refactor_script,
    suggest_architecture,
)


def test_suggest_architecture_returns_empty_payload_without_files() -> None:
    suggestions = suggest_architecture({"nodes": [], "edges": []})

    assert suggestions == {
        "groups": [],
        "groupAssignments": {},
        "simpleMap": {},
        "moves": [],
        "suggestedLayout": {},
        "summary": "No source files were found, so there is nothing to reorganize.",
    }


def test_suggest_architecture_groups_files_by_domain_proximity() -> None:
    report = {
        "nodes": [
            {"id": "src/auth/login.py", "type": "file"},
            {"id": "src/auth/register.py", "type": "file"},
            {"id": "src/payments/payment.py", "type": "file"},
            {"id": "src/users/profile.py", "type": "file"},
        ],
        "edges": [
            {"source": "src/auth/login.py", "target": "src/users/profile.py"},
            {"source": "src/auth/register.py", "target": "src/users/profile.py"},
            {"source": "src/auth/login.py", "target": "src/payments/payment.py"},
        ],
    }

    suggestions = suggest_architecture(report, max_groups=4)

    assert suggestions["summary"] == "Suggested architecture groups: /auth, /payments, /users."
    assert suggestions["groupAssignments"] == {
        "src/auth/login.py": "auth",
        "src/auth/register.py": "auth",
        "src/payments/payment.py": "payments",
        "src/users/profile.py": "users",
    }
    assert suggestions["simpleMap"] == {"auth": ["payments", "users"]}
    assert suggestions["suggestedLayout"] == {
        "auth": ["auth/login.py", "auth/register.py"],
        "payments": ["payments/payment.py"],
        "users": ["users/profile.py"],
    }
    assert suggestions["moves"] == [
        {"source": "src/auth/login.py", "target": "auth/login.py", "group": "auth"},
        {"source": "src/auth/register.py", "target": "auth/register.py", "group": "auth"},
        {
            "source": "src/payments/payment.py",
            "target": "payments/payment.py",
            "group": "payments",
        },
        {"source": "src/users/profile.py", "target": "users/profile.py", "group": "users"},
    ]
    assert suggestions["groups"][0]["name"] == "auth"
    assert suggestions["groups"][0]["count"] == 2
    assert "dependency proximity" in suggestions["groups"][0]["reason"]


def test_suggest_architecture_qualifies_duplicate_file_names() -> None:
    report = {
        "nodes": [
            {"id": "src/auth/index.ts", "type": "file"},
            {"id": "src/auth/api/index.ts", "type": "file"},
        ],
        "edges": [],
    }

    suggestions = suggest_architecture(report, max_groups=4)

    assert suggestions["suggestedLayout"] == {
        "auth": ["auth/api-index.ts", "auth/auth-index.ts"],
    }


def test_suggest_architecture_uses_parent_name_when_tokens_are_not_meaningful() -> None:
    report = {
        "nodes": [
            {"id": "src/auth/index.ts", "type": "file"},
            {"id": "src/auth/x/index.ts", "type": "file"},
        ],
        "edges": [],
    }

    suggestions = suggest_architecture(report, max_groups=4)

    assert suggestions["suggestedLayout"] == {
        "auth": ["auth/auth-index.ts", "auth/x-index.ts"],
    }


def test_generate_refactor_script_returns_message_without_moves() -> None:
    script = generate_refactor_script({"moves": []})

    assert script == "# No file moves were suggested.\n"


def test_generate_refactor_script_supports_bash_output() -> None:
    suggestions = {
        "moves": [
            {"source": "src/auth/login.py", "target": "auth/login.py"},
            {"source": "src/payments/payment.py", "target": "payments/payment.py"},
        ]
    }

    script = generate_refactor_script(suggestions, shell="bash")

    assert script.splitlines() == [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by `archmap improve`",
        "mkdir -p 'auth'",
        "mv 'src/auth/login.py' 'auth/login.py'",
        "mkdir -p 'payments'",
        "mv 'src/payments/payment.py' 'payments/payment.py'",
    ]
