from __future__ import annotations

import os
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from archmap.utils.file_utils import normalize_file_id

GROUP_WRAPPERS = {"src", "app", "lib", "packages", "services"}
GENERIC_TOKENS = {
    "",
    ".",
    "__init__",
    "adapter",
    "adapters",
    "api",
    "app",
    "apps",
    "bin",
    "build",
    "cli",
    "client",
    "common",
    "component",
    "components",
    "config",
    "configs",
    "controller",
    "controllers",
    "core",
    "database",
    "db",
    "domain",
    "dto",
    "entities",
    "entity",
    "feature",
    "features",
    "handler",
    "handlers",
    "helper",
    "helpers",
    "impl",
    "index",
    "infra",
    "infrastructure",
    "interface",
    "job",
    "jobs",
    "lib",
    "main",
    "model",
    "models",
    "module",
    "modules",
    "page",
    "pages",
    "pkg",
    "provider",
    "providers",
    "repo",
    "repository",
    "repositories",
    "route",
    "routes",
    "screen",
    "screens",
    "server",
    "service",
    "services",
    "shared",
    "src",
    "store",
    "stores",
    "test",
    "tests",
    "types",
    "ui",
    "util",
    "utils",
    "view",
    "views",
    "web",
}
TOKEN_PATTERN = re.compile(r"[a-z0-9]+")


def suggest_architecture(report: dict[str, Any], max_groups: int = 8) -> dict:
    file_nodes = [node for node in report.get("nodes", []) if node.get("type") == "file"]
    if not file_nodes:
        return {
            "groups": [],
            "groupAssignments": {},
            "simpleMap": {},
            "moves": [],
            "suggestedLayout": {},
            "summary": "No source files were found, so there is nothing to reorganize.",
        }

    file_ids = [str(node["id"]) for node in file_nodes]
    file_set = set(file_ids)
    adjacency = _build_file_adjacency(report.get("edges", []), file_set)
    current_groups = {file_id: _current_group(file_id) for file_id in file_ids}
    assignments = {
        file_id: _suggest_group_for_file(file_id, adjacency[file_id], current_groups)
        for file_id in file_ids
    }
    assignments = _collapse_small_groups(assignments, max_groups=max(2, max_groups))
    basename_counts = _compute_basename_counts(assignments)
    suggested_layout = _build_suggested_layout(assignments, basename_counts)
    moves = _build_move_plan(assignments, basename_counts)
    simple_map = _build_group_graph(report.get("edges", []), assignments)

    groups = []
    sorted_groups = sorted(
        suggested_layout,
        key=lambda item: (-len(suggested_layout[item]), item),
    )
    for group_name in sorted_groups:
        files = suggested_layout[group_name]
        groups.append(
            {
                "name": group_name,
                "files": files,
                "count": len(files),
                "reason": _group_reason(group_name, files),
            }
        )

    return {
        "groups": groups,
        "groupAssignments": assignments,
        "simpleMap": simple_map,
        "moves": moves,
        "suggestedLayout": suggested_layout,
        "summary": _summary_for_groups(groups),
    }


def generate_refactor_script(suggestions: dict, shell: str | None = None) -> str:
    moves = suggestions.get("moves", [])
    if not moves:
        return "# No file moves were suggested.\n"

    active_shell = shell or ("powershell" if os.name == "nt" else "bash")
    if active_shell == "powershell":
        lines = [
            "# Generated by `archmap improve`",
            "$ErrorActionPreference = 'Stop'",
            "",
        ]
        for move in moves:
            target_dir = Path(move["target"]).parent.as_posix()
            lines.append(f"New-Item -ItemType Directory -Force -Path '{target_dir}' | Out-Null")
            lines.append(
                f"Move-Item -LiteralPath '{move['source']}' "
                f"-Destination '{move['target']}'"
            )
        return "\n".join(lines) + "\n"

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by `archmap improve`",
    ]
    for move in moves:
        target_dir = Path(move["target"]).parent.as_posix()
        lines.append(f"mkdir -p '{target_dir}'")
        lines.append(f"mv '{move['source']}' '{move['target']}'")
    return "\n".join(lines) + "\n"


def _build_file_adjacency(edges: list[dict], file_set: set[str]) -> dict[str, set[str]]:
    adjacency: dict[str, set[str]] = {file_id: set() for file_id in file_set}
    for edge in edges:
        source = str(edge.get("source", ""))
        target = str(edge.get("target", ""))
        if source not in file_set or target not in file_set:
            continue
        adjacency[source].add(target)
        adjacency[target].add(source)
    return adjacency


def _suggest_group_for_file(
    file_id: str,
    neighbors: set[str],
    current_groups: dict[str, str],
) -> str:
    """Suggest a target group using file-name hints plus dependency proximity.

    The current group keeps a heavier baseline score, while neighbors still
    influence the result so tightly coupled files tend to land in the same
    cluster. This means large hubs can be pulled toward the group implied by
    their dependency neighborhood.
    """
    scores: Counter[str] = Counter()
    current_group = current_groups.get(file_id, "")
    if current_group:
        scores[current_group] += 4 if current_group in GENERIC_TOKENS else 6

    for token in _meaningful_tokens(file_id):
        scores[token] += 3

    for neighbor in neighbors:
        neighbor_group = current_groups.get(neighbor, "")
        if neighbor_group:
            scores[neighbor_group] += 1 if neighbor_group in GENERIC_TOKENS else 2
        for token in _meaningful_tokens(neighbor):
            scores[token] += 1

    if scores:
        return sorted(scores.items(), key=lambda item: (-item[1], item[0]))[0][0]

    if current_group:
        return current_group

    return "shared"


def _collapse_small_groups(assignments: dict[str, str], max_groups: int) -> dict[str, str]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for file_id, group in assignments.items():
        grouped[group].append(file_id)

    ranked_groups = sorted(grouped, key=lambda item: (-len(grouped[item]), item))
    keep = set(ranked_groups[:max_groups])
    collapsed: dict[str, str] = {}
    for file_id, group in assignments.items():
        collapsed[file_id] = group if group in keep else "shared"
    return collapsed


def _compute_basename_counts(assignments: dict[str, str]) -> dict[str, Counter[str]]:
    counts: dict[str, Counter[str]] = defaultdict(Counter)
    for file_id, group in assignments.items():
        counts[group][Path(file_id).name] += 1
    return counts


def _build_suggested_layout(
    assignments: dict[str, str],
    basename_counts: dict[str, Counter[str]],
) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)

    for file_id, group in assignments.items():
        target = _target_path_for_file(file_id, group, basename_counts[group])
        grouped[group].append(target)

    for group in grouped:
        grouped[group].sort()
    return dict(grouped)


def _build_move_plan(
    assignments: dict[str, str],
    basename_counts: dict[str, Counter[str]],
) -> list[dict]:
    grouped_files: dict[str, list[str]] = defaultdict(list)
    for file_id, group in assignments.items():
        grouped_files[group].append(file_id)

    moves: list[dict] = []
    for group, files in grouped_files.items():
        for file_id in sorted(files):
            target = _target_path_for_file(file_id, group, basename_counts[group])
            if normalize_file_id(file_id) == normalize_file_id(target):
                continue
            moves.append(
                {
                    "source": normalize_file_id(file_id),
                    "target": normalize_file_id(target),
                    "group": group,
                }
            )
    return moves


def _build_group_graph(edges: list[dict], assignments: dict[str, str]) -> dict[str, list[str]]:
    adjacency: dict[str, set[str]] = defaultdict(set)
    for edge in edges:
        source = str(edge.get("source", ""))
        target = str(edge.get("target", ""))
        if source not in assignments or target not in assignments:
            continue
        source_group = assignments[source]
        target_group = assignments[target]
        if source_group == target_group:
            continue
        adjacency[source_group].add(target_group)

    return {
        group: sorted(targets)
        for group, targets in sorted(adjacency.items(), key=lambda item: item[0])
    }


def _group_reason(group_name: str, files: list[str]) -> str:
    sample = ", ".join(Path(file_path).name for file_path in files[:3])
    return (
        f"Grouped around the '{group_name}' domain based on file names "
        f"and dependency proximity ({sample})."
    )


def _summary_for_groups(groups: list[dict]) -> str:
    if not groups:
        return "No reorganization suggestions were generated."
    top_groups = ", ".join(f"/{group['name']}" for group in groups[:5])
    return f"Suggested architecture groups: {top_groups}."


def _target_path_for_file(file_id: str, group: str, group_basename_counts: Counter[str]) -> str:
    basename = Path(file_id).name
    if group_basename_counts[basename] == 1:
        return normalize_file_id(f"{group}/{basename}")

    stem = Path(file_id).stem
    suffix = Path(file_id).suffix
    parent_tokens = [
        token
        for token in _meaningful_tokens(Path(file_id).parent.as_posix())
        if token != group
    ]
    qualifier = parent_tokens[0] if parent_tokens else _fallback_parent_qualifier(file_id, group)
    return normalize_file_id(f"{group}/{qualifier}-{stem}{suffix}")


def _current_group(file_id: str) -> str:
    parts = [
        part.casefold()
        for part in normalize_file_id(file_id).split("/")
        if part and part != "."
    ]
    if not parts:
        return "shared"
    if len(parts) == 1:
        return "shared"
    if parts[0] in GROUP_WRAPPERS and len(parts) > 1:
        if Path(parts[1]).suffix:
            return parts[0]
        return parts[1]
    if Path(parts[0]).suffix:
        return "shared"
    return parts[0]


def _meaningful_tokens(path_value: str) -> list[str]:
    normalized = normalize_file_id(path_value).casefold()
    tokens: list[str] = []
    for part in normalized.split("/"):
        if not part or part == ".":
            continue
        stem = Path(part).stem.casefold()
        for token in TOKEN_PATTERN.findall(stem):
            if token not in GENERIC_TOKENS and len(token) > 1:
                tokens.append(token)
    return tokens


def _fallback_parent_qualifier(file_id: str, group: str) -> str:
    parent_name = normalize_file_id(Path(file_id).parent.name)
    return parent_name or "module"
